name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Ensure Ruby is installed
        run: |
          ruby -v  # Confirm Ruby version
          which ruby  # Confirm Ruby path

      - name: Fix Ruby shebang in bin scripts
        run: |
          for file in bin/*; do
            # Update shebang to use ruby instead of ruby.exe
            sed -i 's/ruby.exe/ruby/' "$file"
          done
        shell: bash

      - name: Verify shebang lines in bin scripts
        run: head -n 1 bin/*  # Prints the first line of each script for verification

      - name: Set execute permissions on scripts
        run: chmod +x bin/*

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Grant execute permissions to all files in bin/
        run: chmod +x bin/*

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Grant execute permissions to all files in bin/
        run: chmod +x bin/*

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Ensure Ruby is installed
        run: |
          ruby -v  # Confirm Ruby version
          which ruby  # Confirm Ruby path

      - name: Fix Ruby shebang in bin scripts
        run: |
          for file in bin/*; do
            # Ensure Ruby is used instead of ruby.exe in the shebang
            if [ -f "$file" ]; then
              sed -i 's|ruby.exe|ruby|' "$file"  # Replace ruby.exe with ruby
            fi
          done
        shell: bash

      - name: Verify shebang lines in bin scripts
        run: |
          for file in bin/*; do
            # Print the first line of each file to confirm shebang is fixed
            head -n 1 "$file"
          done

      - name: Grant execute permissions to all files in bin/
        run: chmod +x bin/*

      - name: Setup Database
        run: |
          bin/rails db:create db:migrate RAILS_ENV=test

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bin/rails test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
